class Settings:
    def __init__(self):
        #画面の設定
        self.display={
                "width":600,
                "height":800
        }
        #ステージの設定
        self.stage={
                "bg_color":(0,0,0),
                "lag":500
        }
        #ゲームオーバー画面の設定
        self.gameover={
                "fontsize1":100,
                "bg_color":(0,0,50),
                "fg_color1":(50,50,0)
        }
        #スコアボードの設定
        self.scoreboard={
                "width":200,
                "bg_color":(120,120,120),
                "fg_color":(0,0,0),
                "fontsize":30
        }
        #プレイヤーの設定
        self.player={
                "coll_size":4,
                "size":10,
                "x":300,
                "y":700,
                "color":(255,0,0),
                "coll_color":(255,255,255),
                "speed":5,
                "slow":1.5,
                "power":1,
                "max_power":5,
                "item_coll":100,
                "life":5
        }
        #プレイヤーの弾の設定
        self.player_bullet1={
                "size":5,
                "color":(100,100,100),
                "speed":7,
                "timing":3
        }
        self.player_bullet2={
                "size":3,
                "color":(120,120,120),
                "speed":8,
                "timing":3,
                "angle":10
        }
        #敵の設定
        self.enemy1={
                "size":10,
                "color":(120,0,120),
                "speed":3,
                "timing":7,
                "height":300,
                "points":50,
                "height1":200,
                "height2":600,
                "max_enemys":300/1
        }
        self.enemy2={
                "pos1":(150,150),
                "pos2":(450,150),
                "size1":15,
                "size2":10,
                "color1":(0,255,0),
                "color2":(0,0,0),
                "points":80,
                "life":200
        }
        self.enemy3={
                "amount":3,
                "size1":15,
                "size2":10,
                "circle_size":150,
                "color1":(128,0,0),
                "color2":(255,0,0),
                "points":100,
                "speed":1,
                "life":300
        }
        self.enemy4={
                "size1":20,
                "size2":10,
                "color1":(0,255,0),
                "color2":(0,0,0),
                "points":120,
                "life":400
        }
        self.enemy5={
                "y":150,
                "size":20,
                "move_dis":200,
                "color":(0,255,255),
                "speed":5,
                "points":140,
                "life":500
        }
        self.enemy6={
                "size":20,
                "color":(255,0,0),
                "points":160,
                "life":600,
                "timing":100
        }
        #敵の弾の設定
        self.enemy_bullet2={
                "size1":8,
                "size2":4,
                "color1":(0,128,0),
                "color2":(255,255,255),
                "speed":2,
                "timing":20,
                "interval1":100,
                "interval2":100,
                "angle_step":20,
                "append_rate":3
        }
        self.enemy_bullet3={
                "size1":8,
                "size2":4,
                "color":(253,126,0),
                "speed":2,
                "timing":20
        }
        self.enemy_bullet4={
                "size1":8,
                "size2":4,
                "color":(0,255,0),
                "speed":2,
                "timing":5,
                "step":30
        }
        self.enemy_bullet5={
                "size1":8,
                "size2":2,
                "color1":(255,255,0),
                "color2":(0,255,255),
                "speed1":15,
                "speed2":1
        }
        self.enemy_bullet6={
                "size":2,
                "color1":(255,0,0),
                "color2":(255,255,0),
                "speed":1
        }
        #敵のドロップアイテムの設定
        self.item1={
                "size1":10,
                "size2":5,
                "color1":(0,0,255),
                "color2":(255,255,255),
                "speed1":0.2,
                "speed2":1,
                "speed3":5,
                "power":0.03,
                "prob":20
        }
